import { KPU_DPT_PONOROGO_2024 } from '../../utils/electoralData';

// Struktur Tim Relawan & Saksi (21 Korcam Se-Ponorogo + Kordes + Saksi TPS dengan status kehadiran riil)
export const SEED_RELAWAN = [
  // 21 Koordinator Kecamatan (KORCAM) Resmi Berbasis Data KPU 2024
  ...KPU_DPT_PONOROGO_2024.map((k, idx) => ({
    id: `USR-KORCAM-${k.nama.toUpperCase().replace(/[^A-Z]/g, '')}`,
    nama: k.picKorcam,
    nik: `3502${String(k.no).padStart(2, '0')}1508${75 + (idx % 20)}${String(idx + 1).padStart(4, '0')}`,
    email: `korcam.${k.nama.toLowerCase().replace(/[^a-z]/g, '')}@pemenangan.id`,
    nomor_wa: `081234567${String(800 + idx)}`,
    tingkat_penugasan: 'KORCAM (Koordinator Kecamatan)',
    parent_coordinator: 'Tim Pemenangan Utama Caleg Ponorogo',
    provinsi_tugas: 'Jawa Timur',
    kota_tugas: 'Kabupaten Ponorogo',
    kecamatan_tugas: `Kecamatan ${k.nama}`,
    desa_tugas: '',
    tps_tugas: '',
    role: 'KORCAM',
    status: 'AKTIF',
    tenant_id: 'TNT-DEFAULT',
    foto_relawan: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80'
    ][idx % 5],
    createdAt: new Date().toISOString()
  })),

  // Koordinator Desa (KORDES) Strategis Berpengaruh
  {
    id: 'USR-KORDES-MNG',
    nama: 'Ahmad Fauzi, S.Kom.',
    nik: '3502012308900002',
    email: 'kordes.mangkujayan@pemenangan.id',
    nomor_wa: '081234567892',
    tingkat_penugasan: 'KORDES (Koordinator Desa/Kelurahan)',
    parent_coordinator: 'Budi Santoso, S.Pd. (Korcam Ponorogo Kota)',
    provinsi_tugas: 'Jawa Timur',
    kota_tugas: 'Kabupaten Ponorogo',
    kecamatan_tugas: 'Kecamatan Ponorogo (Kota)',
    desa_tugas: 'Kelurahan Mangkujayan',
    tps_tugas: '',
    role: 'RELAWAN_LAPANGAN',
    status: 'AKTIF',
    tenant_id: 'TNT-DEFAULT',
    foto_relawan: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString()
  },
  {
    id: 'USR-KORDES-NGUNUT',
    nama: 'Muhammad Ridwan (Ketua Paguyuban Reyog)',
    nik: '3502021106880004',
    email: 'kordes.ngunut@pemenangan.id',
    nomor_wa: '081234567896',
    tingkat_penugasan: 'KORDES (Koordinator Desa/Kelurahan)',
    parent_coordinator: 'Suryadi, S.Sos. (Korcam Babadan)',
    provinsi_tugas: 'Jawa Timur',
    kota_tugas: 'Kabupaten Ponorogo',
    kecamatan_tugas: 'Kecamatan Babadan',
    desa_tugas: 'Desa Ngunut',
    tps_tugas: '',
    role: 'RELAWAN_LAPANGAN',
    status: 'AKTIF',
    tenant_id: 'TNT-DEFAULT',
    foto_relawan: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString()
  },
  {
    id: 'USR-KORDES-RONOWIJAYAN',
    nama: 'Kholid Mansur, S.Pd.I.',
    nik: '3502031407890005',
    email: 'kordes.ronowijayan@pemenangan.id',
    nomor_wa: '081234567899',
    tingkat_penugasan: 'KORDES (Koordinator Desa/Kelurahan)',
    parent_coordinator: 'Drs. Hendro Wibowo (Korcam Siman)',
    provinsi_tugas: 'Jawa Timur',
    kota_tugas: 'Kabupaten Ponorogo',
    kecamatan_tugas: 'Kecamatan Siman',
    desa_tugas: 'Desa Ronowijayan',
    tps_tugas: '',
    role: 'RELAWAN_LAPANGAN',
    status: 'AKTIF',
    tenant_id: 'TNT-DEFAULT',
    foto_relawan: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString()
  },

  // Saksi TPS Terverifikasi dengan Ragam Kasus Realistis
  {
    id: 'USR-SAKSI-TPS07',
    nama: 'Siti Rahmawati (Saksi Utama)',
    nik: '3502015509930003',
    email: 'saksi.tps07.mangkujayan@pemenangan.id',
    nomor_wa: '081234567893',
    tingkat_penugasan: 'SAKSI_TPS (Saksi TPS Resmi)',
    parent_coordinator: 'Ahmad Fauzi (Kordes Mangkujayan)',
    provinsi_tugas: 'Jawa Timur',
    kota_tugas: 'Kabupaten Ponorogo',
    kecamatan_tugas: 'Kecamatan Ponorogo (Kota)',
    desa_tugas: 'Kelurahan Mangkujayan',
    tps_tugas: 'TPS 007',
    status_kehadiran_tps: 'SELESAI_SERAHKAN_C1',
    honor_tps: 200000,
    status_pencairan_honor: 'SUDAH_TRANSFER_C1_VALID',
    rekening_ewallet_saksi: 'BCA 873-509-2211 a.n Siti Rahmawati',
    role: 'RELAWAN_LAPANGAN',
    status: 'AKTIF',
    tenant_id: 'TNT-DEFAULT',
    foto_relawan: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString()
  },
  {
    id: 'USR-SAKSI-TPS03-NGUNUT',
    nama: 'Tri Wahyudi, S.T.',
    nik: '3502022405950005',
    email: 'saksi.tps03.ngunut@pemenangan.id',
    nomor_wa: '081234567897',
    tingkat_penugasan: 'SAKSI_TPS (Saksi TPS Resmi)',
    parent_coordinator: 'Muhammad Ridwan (Kordes Ngunut)',
    provinsi_tugas: 'Jawa Timur',
    kota_tugas: 'Kabupaten Ponorogo',
    kecamatan_tugas: 'Kecamatan Babadan',
    desa_tugas: 'Desa Ngunut',
    tps_tugas: 'TPS 003',
    status_kehadiran_tps: 'SELESAI_SERAHKAN_C1',
    honor_tps: 200000,
    status_pencairan_honor: 'SUDAH_TRANSFER_C1_VALID',
    rekening_ewallet_saksi: 'BRI 012-345-6789 a.n Tri Wahyudi',
    role: 'RELAWAN_LAPANGAN',
    status: 'AKTIF',
    tenant_id: 'TNT-DEFAULT',
    foto_relawan: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString()
  },
  {
    id: 'USR-SAKSI-TPS05-SIMAN',
    nama: 'Nurul Hidayah, S.Pd.I.',
    nik: '3502035208940006',
    email: 'saksi.tps05.siman@pemenangan.id',
    nomor_wa: '081234567898',
    tingkat_penugasan: 'SAKSI_TPS (Saksi TPS Resmi)',
    parent_coordinator: 'Drs. Hendro Wibowo (Korcam Siman)',
    provinsi_tugas: 'Jawa Timur',
    kota_tugas: 'Kabupaten Ponorogo',
    kecamatan_tugas: 'Kecamatan Siman',
    desa_tugas: 'Desa Siman',
    tps_tugas: 'TPS 005',
    status_kehadiran_tps: 'SEDANG_REKAP_HITUNG',
    honor_tps: 200000,
    status_pencairan_honor: 'SIAP_DICAIRKAN',
    rekening_ewallet_saksi: 'DANA 081234567898',
    role: 'RELAWAN_LAPANGAN',
    status: 'AKTIF',
    tenant_id: 'TNT-DEFAULT',
    foto_relawan: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString()
  },
  {
    id: 'USR-SAKSI-LOKSUS-GONTOR',
    nama: 'Ust. Fathur Rahman, S.Ag.',
    nik: '3502071504910008',
    email: 'saksi.loksus.gontor@pemenangan.id',
    nomor_wa: '081234567811',
    tingkat_penugasan: 'SAKSI_TPS (Saksi TPS Resmi)',
    parent_coordinator: 'Kyai Ahmad Hasan (Korcam Mlarak)',
    provinsi_tugas: 'Jawa Timur',
    kota_tugas: 'Kabupaten Ponorogo',
    kecamatan_tugas: 'Kecamatan Mlarak',
    desa_tugas: 'Desa Gontor',
    tps_tugas: 'TPS 901',
    status_kehadiran_tps: 'STANDBY_BUKA_TPS',
    honor_tps: 250000,
    status_pencairan_honor: 'SIAP_DICAIRKAN',
    rekening_ewallet_saksi: 'BSI 712-345-6789 a.n Fathur Rahman',
    role: 'RELAWAN_LAPANGAN',
    status: 'AKTIF',
    tenant_id: 'TNT-DEFAULT',
    foto_relawan: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString()
  },
  // Anomali Saksi 1: Belum Hadir (Alert Sistem)
  {
    id: 'USR-SAKSI-TPS04-ALERT',
    nama: 'Dodi Prasetyo (Peringatan Saksi Cadangan)',
    nik: '3502061205960009',
    email: 'saksi.tps04.sukorejo@pemenangan.id',
    nomor_wa: '081234567819',
    tingkat_penugasan: 'SAKSI_TPS (Saksi TPS Resmi)',
    parent_coordinator: 'Purwanto, S.E. (Korcam Sukorejo)',
    provinsi_tugas: 'Jawa Timur',
    kota_tugas: 'Kabupaten Ponorogo',
    kecamatan_tugas: 'Kecamatan Sukorejo',
    desa_tugas: 'Desa Sukorejo',
    tps_tugas: 'TPS 004',
    status_kehadiran_tps: 'BELUM_HADIR',
    honor_tps: 200000,
    status_pencairan_honor: 'BELUM_CAIR',
    rekening_ewallet_saksi: 'BRI 012-778-9900 a.n Dodi Prasetyo',
    role: 'RELAWAN_LAPANGAN',
    status: 'AKTIF',
    tenant_id: 'TNT-DEFAULT',
    foto_relawan: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString()
  },
  // Anomali Saksi 2: C1 Tidak Lengkap / Halaman 2 Buram
  {
    id: 'USR-SAKSI-TPS02-HOLD',
    nama: 'Agus Santoso',
    nik: '3502031908920011',
    email: 'saksi.tps02.slahung@pemenangan.id',
    nomor_wa: '081234567825',
    tingkat_penugasan: 'SAKSI_TPS (Saksi TPS Resmi)',
    parent_coordinator: 'Marno, S.Pd. (Korcam Slahung)',
    provinsi_tugas: 'Jawa Timur',
    kota_tugas: 'Kabupaten Ponorogo',
    kecamatan_tugas: 'Kecamatan Slahung',
    desa_tugas: 'Desa Slahung',
    tps_tugas: 'TPS 002',
    status_kehadiran_tps: 'SEDANG_REKAP_HITUNG',
    honor_tps: 200000,
    status_pencairan_honor: 'DITAHAN_C1_BELUM_LENGKAP',
    rekening_ewallet_saksi: 'BCA 873-445-1100 a.n Agus Santoso',
    role: 'RELAWAN_LAPANGAN',
    status: 'AKTIF',
    tenant_id: 'TNT-DEFAULT',
    foto_relawan: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString()
  }
];

// Master DPT Pemilih KPU (Distribusi 21 Kecamatan Ponorogo dengan TPS Reguler & Loksus)
export const SEED_DPT = [
  {
    id: 'DPT-350201-0001',
    nik: '3502011102780001',
    nama: 'Bambang Supriyanto',
    jenis_kelamin: 'Laki-laki',
    usia: 48,
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Ponorogo (Kota)',
    desa: 'Kelurahan Mangkujayan',
    rw: '03',
    rt: '02',
    nomor_tps: 'TPS 007',
    kategori_tps: 'TPS_REGULER',
    status_afiliasi: 'LOYALIS_PASTI',
    catatan_afiliasi: 'Ketua RW 03 Mangkujayan dekat Alun-alun Ponorogo, menggalang 45 suara keluarga besar.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'DPT-350201-LOK01',
    nik: '3502011204890015',
    nama: 'Ust. Ahmad Zarkasyi (Santri Gontor 1)',
    jenis_kelamin: 'Laki-laki',
    usia: 24,
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Mlarak',
    desa: 'Desa Gontor',
    rw: '02',
    rt: '01',
    nomor_tps: 'TPS 901',
    kategori_tps: 'TPS_LOKSUS_PESANTREN',
    status_afiliasi: 'LOYALIS_PASTI',
    catatan_afiliasi: 'Pemilih TPS Lokasi Khusus Pondok Gontor Putra 1. Jaringan alumni pesantren kompak.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'DPT-350201-LOK02',
    nik: '3502014809800016',
    nama: 'H. Sudarsono (Binaan Rutan Ponorogo)',
    jenis_kelamin: 'Laki-laki',
    usia: 49,
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Ponorogo (Kota)',
    desa: 'Kelurahan Mangkujayan',
    rw: '01',
    rt: '01',
    nomor_tps: 'TPS 901',
    kategori_tps: 'TPS_LOKSUS_RUTAN',
    status_afiliasi: 'TARGET_PROSPEK',
    catatan_afiliasi: 'Pemilih binaan TPS Lokasi Khusus Rutan Kelas IIB Ponorogo.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'DPT-350201-0002',
    nik: '3502014506820002',
    nama: 'Hj. Sri Wahyuni, S.Pd.',
    jenis_kelamin: 'Perempuan',
    usia: 44,
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Ponorogo (Kota)',
    desa: 'Kelurahan Mangkujayan',
    rw: '03',
    rt: '02',
    nomor_tps: 'TPS 007',
    kategori_tps: 'TPS_REGULER',
    status_afiliasi: 'LOYALIS_PASTI',
    catatan_afiliasi: 'Koordinator Paguyuban Guru PAUD & Muslimat NU Ponorogo Kota.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'DPT-350201-0003',
    nik: '3502012108950003',
    nama: 'Dimas Anggara Pratama (Warok Muda)',
    jenis_kelamin: 'Laki-laki',
    usia: 30,
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Babadan',
    desa: 'Desa Ngunut',
    rw: '01',
    rt: '04',
    nomor_tps: 'TPS 003',
    kategori_tps: 'TPS_REGULER',
    status_afiliasi: 'SWING_VOTER',
    catatan_afiliasi: 'Pemuda penggerak sanggar reyog Singo Taruno Babadan, apresiatif program pelestarian budaya.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'DPT-350201-0004',
    nik: '3502015203870004',
    nama: 'Endang Purwaningsih, S.E.',
    jenis_kelamin: 'Perempuan',
    usia: 39,
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Ponorogo (Kota)',
    desa: 'Kelurahan Kauman',
    rw: '02',
    rt: '01',
    nomor_tps: 'TPS 004',
    kategori_tps: 'TPS_REGULER',
    status_afiliasi: 'LOYALIS_PASTI',
    catatan_afiliasi: 'Pengurus Fatayat NU ranting Kauman.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'DPT-350201-0005',
    nik: '3502011904790005',
    nama: 'Suprapto Edi',
    jenis_kelamin: 'Laki-laki',
    usia: 47,
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Siman',
    desa: 'Desa Siman',
    rw: '04',
    rt: '02',
    nomor_tps: 'TPS 005',
    kategori_tps: 'TPS_REGULER',
    status_afiliasi: 'LOYALIS_PASTI',
    catatan_afiliasi: 'Ketua kelompok tani makmur Siman, penerima program Pokir alsintan.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'DPT-350201-0006',
    nik: '3502016307920006',
    nama: 'Rina Astuti, S.E.',
    jenis_kelamin: 'Perempuan',
    usia: 34,
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Siman',
    desa: 'Desa Ronowijayan',
    rw: '01',
    rt: '03',
    nomor_tps: 'TPS 002',
    kategori_tps: 'TPS_REGULER',
    status_afiliasi: 'TARGET_PROSPEK',
    catatan_afiliasi: 'Pelaku UMKM kuliner sentra sate Ponorogo gang 2.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'DPT-350201-0007',
    nik: '3502010811830007',
    nama: 'Hariyanto (Tokoh Pasar)',
    jenis_kelamin: 'Laki-laki',
    usia: 43,
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Babadan',
    desa: 'Desa Babadan',
    rw: '02',
    rt: '03',
    nomor_tps: 'TPS 001',
    kategori_tps: 'TPS_REGULER',
    status_afiliasi: 'LOYALIS_PASTI',
    catatan_afiliasi: 'Tokoh paguyuban pedagang pasar Babadan.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'DPT-350201-0008',
    nik: '3502041203850008',
    nama: 'Wahid Hasyim',
    jenis_kelamin: 'Laki-laki',
    usia: 39,
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Slahung',
    desa: 'Desa Slahung',
    rw: '02',
    rt: '01',
    nomor_tps: 'TPS 002',
    kategori_tps: 'TPS_REGULER',
    status_afiliasi: 'SWING_VOTER',
    catatan_afiliasi: 'Petani cengkeh Slahung, butuh kepastian pupuk bersubsidi.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'DPT-350201-0009',
    nik: '3502062509900009',
    nama: 'Ratna Dewi Kusuma',
    jenis_kelamin: 'Perempuan',
    usia: 34,
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Sukorejo',
    desa: 'Desa Sukorejo',
    rw: '03',
    rt: '02',
    nomor_tps: 'TPS 004',
    kategori_tps: 'TPS_REGULER',
    status_afiliasi: 'LOYALIS_PASTI',
    catatan_afiliasi: 'Pengurus Fatayat NU ranting Sukorejo.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  }
];

// Database Konstituen (KTP Realistis & Bersebaran Berbasis Bukti e-KTP Valid)
export const SEED_KONSTITUEN = [
  {
    id: 'KST-3502-001',
    nik: '3502011102780001',
    name: 'Bambang Supriyanto',
    gender: 'Laki-laki',
    phone: '081298765432',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Kecamatan Ponorogo (Kota)',
    desa: 'Kelurahan Mangkujayan',
    rw: '03',
    rt: '02',
    nomor_tps: 'TPS 007',
    skor_kepastian: 'PASTI_COBLOS_100',
    faktor_pengaruh_kunci: 'KEDEKATAN_PERSONAL_CALEG',
    ktp_image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=60',
    location: '-7.8687, 111.4623',
    input_by: 'kordes.mangkujayan@pemenangan.id',
    notes: 'e-KTP Ponorogo Asli diverifikasi fisik. Lokasi GPS terkonfirmasi di sekitar Alun-alun Ponorogo.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'KST-3502-002',
    nik: '3502014506820002',
    name: 'Hj. Sri Wahyuni, S.Pd.',
    gender: 'Perempuan',
    phone: '081387654321',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Kecamatan Ponorogo (Kota)',
    desa: 'Kelurahan Mangkujayan',
    rw: '03',
    rt: '02',
    nomor_tps: 'TPS 007',
    skor_kepastian: 'PASTI_COBLOS_100',
    faktor_pengaruh_kunci: 'TOKOH_AGAMA_KYAI',
    ktp_image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=60',
    location: '-7.8710, 111.4650',
    input_by: 'kordes.mangkujayan@pemenangan.id',
    notes: 'Dukungan pasti keluarga besar Mangkujayan RT 02 RW 03 (Jaringan Pengajian Ahad Pagi).',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'KST-3502-003',
    nik: '3502015203870004',
    name: 'Endang Purwaningsih, S.E.',
    gender: 'Perempuan',
    phone: '081234567822',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Kecamatan Ponorogo (Kota)',
    desa: 'Kelurahan Kauman',
    rw: '02',
    rt: '01',
    nomor_tps: 'TPS 004',
    skor_kepastian: 'KEMUNGKINAN_BESAR_75',
    faktor_pengaruh_kunci: 'PROGRAM_KERJA_PARTAI',
    ktp_image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=60',
    location: '-7.8650, 111.4580',
    input_by: 'kordes.mangkujayan@pemenangan.id',
    notes: 'Komitmen 100% warga RT 01 RW 02 Kauman Kota.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'KST-3502-004',
    nik: '3502012108950003',
    name: 'Dimas Anggara Pratama',
    gender: 'Laki-laki',
    phone: '081234567833',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Kecamatan Babadan',
    desa: 'Desa Ngunut',
    rw: '01',
    rt: '04',
    nomor_tps: 'TPS 003',
    skor_kepastian: 'RAGU_SWING_50',
    faktor_pengaruh_kunci: 'JARINGAN_KELUARGA_BESAR',
    ktp_image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=60',
    location: '-7.8200, 111.4800',
    input_by: 'kordes.ngunut@pemenangan.id',
    notes: 'Perwakilan pemuda desa penggerak sanggar seni reyog Babadan.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'KST-3502-005',
    nik: '3502011904790005',
    name: 'Suprapto Edi (Ketua Poktan)',
    gender: 'Laki-laki',
    phone: '081234567844',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Kecamatan Siman',
    desa: 'Desa Siman',
    rw: '04',
    rt: '02',
    nomor_tps: 'TPS 005',
    skor_kepastian: 'PASTI_COBLOS_100',
    faktor_pengaruh_kunci: 'BANTUAN_ASPIRASI_POKIR',
    ktp_image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=60',
    location: '-7.8920, 111.4950',
    input_by: 'korcam.siman@pemenangan.id',
    notes: 'Kelompok tani desa Siman, komitmen suara 65 KK penggarap sawah.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'KST-3502-006',
    nik: '3502041203850008',
    name: 'Wahid Hasyim (Petani Slahung)',
    gender: 'Laki-laki',
    phone: '081234567855',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Kecamatan Slahung',
    desa: 'Desa Slahung',
    rw: '02',
    rt: '01',
    nomor_tps: 'TPS 002',
    skor_kepastian: 'RAWAN_PINDAH_25',
    faktor_pengaruh_kunci: 'BANTUAN_ASPIRASI_POKIR',
    ktp_image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=60',
    location: '-8.0050, 111.4320',
    input_by: 'korcam.slahung@pemenangan.id',
    notes: 'Pemilih rawan dipengaruhi caleg kompetitor; butuh kunjungan silaturahmi langsung Caleg sebelum masa tenang.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  }
];

// Hasil Quick Count & C1 Plano TPS (Termasuk Contoh Anomali Audit Selisih Suara)
export const SEED_QUICK_COUNT = [
  {
    id: 'QC-TPS007-MANGKUJAYAN',
    nomor_tps: 'TPS 007',
    kategori_tps: 'TPS_REGULER',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Kecamatan Ponorogo (Kota)',
    desa: 'Kelurahan Mangkujayan',
    nama_saksi: 'Siti Rahmawati',
    no_wa_saksi: '081234567893',
    suara_sah_caleg: 158,
    total_suara_sah: 242,
    suara_tidak_sah: 6,
    total_pengguna_hak_pilih: 248,
    status_audit_matematis: 'AUDIT_MATEMATIS_PAS_VALID',
    foto_form_c1: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&auto=format&fit=crop&q=60',
    titik_lokasi_tps: '-7.8687, 111.4623',
    watermark_hash_forensik: 'C1-FORENSIC-SHA256-8F214A7091BE',
    status_verifikasi: 'TERVERIFIKASI_SAH',
    catatan_kejadian_khusus: 'Penghitungan suara Plano C1 selesai pukul 14.45 WIB dengan aman dan tertib.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'QC-TPS003-NGUNUT',
    nomor_tps: 'TPS 003',
    kategori_tps: 'TPS_REGULER',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Kecamatan Babadan',
    desa: 'Desa Ngunut',
    nama_saksi: 'Tri Wahyudi, S.T.',
    no_wa_saksi: '081234567897',
    suara_sah_caleg: 142,
    total_suara_sah: 235,
    suara_tidak_sah: 8,
    total_pengguna_hak_pilih: 243,
    status_audit_matematis: 'AUDIT_MATEMATIS_PAS_VALID',
    foto_form_c1: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&auto=format&fit=crop&q=60',
    titik_lokasi_tps: '-7.8200, 111.4800',
    watermark_hash_forensik: 'C1-FORENSIC-SHA256-4B829EF7100A',
    status_verifikasi: 'TERVERIFIKASI_SAH',
    catatan_kejadian_khusus: 'Saksi menandatangani berita acara C1 resmi KPPS.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'QC-TPS005-SIMAN',
    nomor_tps: 'TPS 005',
    kategori_tps: 'TPS_REGULER',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Kecamatan Siman',
    desa: 'Desa Siman',
    nama_saksi: 'Nurul Hidayah',
    no_wa_saksi: '081234567898',
    suara_sah_caleg: 165,
    total_suara_sah: 250,
    suara_tidak_sah: 4,
    total_pengguna_hak_pilih: 254,
    status_audit_matematis: 'AUDIT_MATEMATIS_PAS_VALID',
    foto_form_c1: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&auto=format&fit=crop&q=60',
    titik_lokasi_tps: '-7.8920, 111.4950',
    watermark_hash_forensik: 'C1-FORENSIC-SHA256-789ABCDEF012',
    status_verifikasi: 'TERVERIFIKASI_SAH',
    catatan_kejadian_khusus: 'Dominasi mutlak suara caleg nomor urut 1 PKB di basis petani Siman.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'QC-TPS901-LOKSUS-GONTOR',
    nomor_tps: 'TPS 901',
    kategori_tps: 'TPS_LOKSUS_PESANTREN',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Kecamatan Mlarak',
    desa: 'Desa Gontor',
    nama_saksi: 'Ust. Fathur Rahman',
    no_wa_saksi: '081234567811',
    suara_sah_caleg: 215,
    total_suara_sah: 285,
    suara_tidak_sah: 5,
    total_pengguna_hak_pilih: 290,
    status_audit_matematis: 'AUDIT_MATEMATIS_PAS_VALID',
    foto_form_c1: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&auto=format&fit=crop&q=60',
    titik_lokasi_tps: '-7.9150, 111.5120',
    watermark_hash_forensik: 'C1-FORENSIC-SHA256-LOKSUS901-GON77',
    status_verifikasi: 'TERVERIFIKASI_SAH',
    catatan_kejadian_khusus: 'TPS Lokasi Khusus Pondok Modern Darussalam Gontor Putra 1. Partisipasi santri 98.3%.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  // Anomali Audit C1: Selisih Suara Terdeteksi Sistem Otomatis
  {
    id: 'QC-TPS002-WARNING-SLAHUNG',
    nomor_tps: 'TPS 002',
    kategori_tps: 'TPS_REGULER',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Kecamatan Slahung',
    desa: 'Desa Slahung',
    nama_saksi: 'Agus Santoso',
    no_wa_saksi: '081234567825',
    suara_sah_caleg: 98,
    total_suara_sah: 210,
    suara_tidak_sah: 12,
    total_pengguna_hak_pilih: 228,
    status_audit_matematis: 'SELISIH_SUARA_WARNING',
    foto_form_c1: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&auto=format&fit=crop&q=60',
    titik_lokasi_tps: '-8.0050, 111.4320',
    watermark_hash_forensik: 'C1-FORENSIC-SHA256-ANOMALY-SLH02',
    status_verifikasi: 'SELISIH_SUARA_WARNING',
    catatan_kejadian_khusus: 'PERINGATAN AUDIT C1: Suara Sah (210) + Suara Rusak (12) = 222, namun Total Pengguna Hak Pilih tertulis 228 (Selisih 6 suara anomali). Tim advokasi siap mengajukan keberatan di pleno PPK.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  }
];

