// Kamus Standar Harga Pasar Daerah (AI Benchmark BPS/Pemda Ponorogo)
export const SEED_STANDAR_HARGA = [
  {
    id: 'SHD-01-KAOS',
    provinsi: 'Jawa Timur',
    kabupaten_kota: 'Kabupaten Ponorogo',
    kategori_item: 'Bahan Sosialisasi / Kaos & Atribut',
    satuan: 'per potong / kaos combed',
    harga_batas_bawah: 22000,
    harga_batas_atas: 28000,
    harga_median_wajar: 25000,
    catatan_audit_ai: 'Standar harga konveksi lokal Ponorogo dan Solo untuk bahan PE/TC gramasi 24s sablon plastisol.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'SHD-02-HONOR-SAKSI',
    provinsi: 'Jawa Timur',
    kabupaten_kota: 'Kabupaten Ponorogo',
    kategori_item: 'Honor Saksi TPS (Hari-H & Rekap)',
    satuan: 'per orang / hari H',
    harga_batas_bawah: 175000,
    harga_batas_atas: 250000,
    harga_median_wajar: 200000,
    catatan_audit_ai: 'Standar konsensus honor saksi luar bilik di Ponorogo mencakup uang makan dan pulsa input C1.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'SHD-03-BANNER',
    provinsi: 'Jawa Timur',
    kabupaten_kota: 'Kabupaten Ponorogo',
    kategori_item: 'Cetak Spanduk / Banner MMT Outdoor',
    satuan: 'per meter persegi (m2)',
    harga_batas_bawah: 15000,
    harga_batas_atas: 22000,
    harga_median_wajar: 18000,
    catatan_audit_ai: 'Bahan Flexi 280-340 gsm cetak resolusi tinggi percetakan outdoor lokal.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'SHD-04-NASI-BOX',
    provinsi: 'Jawa Timur',
    kabupaten_kota: 'Kabupaten Ponorogo',
    kategori_item: 'Konsumsi / Nasi Box Pertemuan Warga',
    satuan: 'per porsi / box',
    harga_batas_bawah: 18000,
    harga_batas_atas: 25000,
    harga_median_wajar: 22000,
    catatan_audit_ai: 'Standar katering ayam bakar/goreng lengkap air mineral kemasan.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'SHD-05-TRANSPORT',
    provinsi: 'Jawa Timur',
    kabupaten_kota: 'Kabupaten Ponorogo',
    kategori_item: 'Uang Transport Relawan Door-to-Door / Canvasser',
    satuan: 'per orang / hari',
    harga_batas_bawah: 50000,
    harga_batas_atas: 75000,
    harga_median_wajar: 60000,
    catatan_audit_ai: 'Uang bensin dan operasional canvassing door-to-door 25 KK per hari.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'SHD-06-SOUND-TENDA',
    provinsi: 'Jawa Timur',
    kabupaten_kota: 'Kabupaten Ponorogo',
    kategori_item: 'Sewa Sound System & Tenda Pertemuan Warga',
    satuan: 'per paket pertemuan',
    harga_batas_bawah: 800000,
    harga_batas_atas: 1500000,
    harga_median_wajar: 1000000,
    catatan_audit_ai: 'Sewa sound system 2000 watt, 50 kursi, dan 1 plong terop.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'SHD-07-SEMBAKO',
    provinsi: 'Jawa Timur',
    kabupaten_kota: 'Kabupaten Ponorogo',
    kategori_item: 'Paket Sembako / Bantuan Aspirasi Sederhana',
    satuan: 'per paket sembako',
    harga_batas_bawah: 65000,
    harga_batas_atas: 95000,
    harga_median_wajar: 80000,
    catatan_audit_ai: 'Beras 3kg, minyak goreng 1L, gula 1kg sesuai batas toleransi Bawaslu.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  }
];

// Anggaran Kampanye, Audit Deviasi Harga & Cost-per-Vote (CPV)
export const SEED_ANGGARAN_KAMPANYE = [
  {
    id: 'ANG-01-KAOS',
    uraian_kegiatan: 'Pengadaan Kaos Relawan Lapangan Dapil 1 Ponorogo Batch 1',
    kategori_item: 'Bahan Sosialisasi / Kaos & Atribut',
    kecamatan: 'Ponorogo (Kota)',
    volume: 1500,
    satuan: 'potong',
    harga_satuan_diajukan: 24000,
    total_anggaran: 36000000,
    target_suara_alokasi: 1200,
    cpv_terhitung: 30000,
    status_audit_algoritma: 'WAJAR_SESUAI_PASAR',
    alasan_audit_ai: 'Harga diajukan Rp 24.000 berada di bawah median pasar Rp 25.000 (Efisien hemat 4%).',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ANG-02-SAKSI-KOTA',
    uraian_kegiatan: 'Alokasi Honorarium Saksi TPS Resmi Ponorogo Kota',
    kategori_item: 'Honor Saksi TPS (Hari-H & Rekap)',
    kecamatan: 'Ponorogo (Kota)',
    volume: 120,
    satuan: 'orang',
    harga_satuan_diajukan: 200000,
    total_anggaran: 24000000,
    target_suara_alokasi: 9500,
    cpv_terhitung: 2526,
    status_audit_algoritma: 'WAJAR_SESUAI_PASAR',
    alasan_audit_ai: 'Sesuai pagu standar honor saksi Pemilu Ponorogo Rp 200.000 per orang.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ANG-03-BANNER-BBDN',
    uraian_kegiatan: 'Pencetakan Banner MMT Caleg & Spanduk 45 Titik Strategis Babadan',
    kategori_item: 'Cetak Spanduk / Banner MMT Outdoor',
    kecamatan: 'Babadan',
    volume: 250,
    satuan: 'meter persegi (m2)',
    harga_satuan_diajukan: 18000,
    total_anggaran: 4500000,
    target_suara_alokasi: 1000,
    cpv_terhitung: 4500,
    status_audit_algoritma: 'WAJAR_SESUAI_PASAR',
    alasan_audit_ai: 'Tepat pada median batas wajar BPS Rp 18.000/m2.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ANG-04-KONSUMSI-KORDES',
    uraian_kegiatan: 'Konsumsi Rapat Koordinasi Akbar Kordes se-Dapil 1',
    kategori_item: 'Konsumsi / Nasi Box Pertemuan Warga',
    kecamatan: 'Ponorogo (Kota)',
    volume: 150,
    satuan: 'porsi',
    harga_satuan_diajukan: 22000,
    total_anggaran: 3300000,
    target_suara_alokasi: 1500,
    cpv_terhitung: 2200,
    status_audit_algoritma: 'WAJAR_SESUAI_PASAR',
    alasan_audit_ai: 'Sesuai standar katering konsolidasi lokal.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ANG-05-MARKUP-ALERT',
    uraian_kegiatan: 'Pengadaan Kaos Tambahan dari Vendor Eksternal Batch 2',
    kategori_item: 'Bahan Sosialisasi / Kaos & Atribut',
    kecamatan: 'Babadan',
    volume: 500,
    satuan: 'potong',
    harga_satuan_diajukan: 45000,
    total_anggaran: 22500000,
    target_suara_alokasi: 500,
    cpv_terhitung: 45000,
    status_audit_algoritma: 'PERINGATAN_MARKUP',
    alasan_audit_ai: 'PERINGATAN PEMBOROSAN: Harga diajukan Rp 45.000 melampaui batas atas wajar Rp 28.000 (+60.7%). Direkomendasikan negosiasi ulang!',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'ANG-06-CANVASSING',
    uraian_kegiatan: 'Bantuan Transport Door-to-Door Tim Penggerak Siman',
    kategori_item: 'Uang Transport Relawan Door-to-Door / Canvasser',
    kecamatan: 'Siman',
    volume: 50,
    satuan: 'orang',
    harga_satuan_diajukan: 60000,
    total_anggaran: 3000000,
    target_suara_alokasi: 1200,
    cpv_terhitung: 2500,
    status_audit_algoritma: 'WAJAR_SESUAI_PASAR',
    alasan_audit_ai: 'Efisiensi canvassing sangat baik dengan rasio CPV Rp 2.500 per suara.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  }
];

// Laporan Pertanggungjawaban (LPJ)
export const SEED_LPJ_KEGIATAN = [
  {
    id: 'LPJ-2024-001',
    nomor_rab_terkait: 'RAB-PNG-SAKSI-01',
    kegiatan: 'Alokasi Honorarium & Pelatihan Saksi TPS Ponorogo Kota',
    pic: 'Budi Santoso, S.Pd.',
    kecamatan: 'Ponorogo (Kota)',
    desa: 'Kelurahan Mangkujayan',
    dana_diterima: 25200000,
    nominal_terpakai: 24700000,
    sisa_kas_silpa: 500000,
    status_silpa: 'LEBIH_KEMBALIKAN_KAS',
    foto_bukti: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
    lokasi: '-7.8687, 111.4623',
    status_audit: 'SAH_SESUAI_KTP',
    bukti_setor_silpa: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop&q=80',
    catatan_lpj: 'Honor 120 saksi tersalurkan 100%. Sisa dana darurat Rp 500.000 telah ditransfer balik ke kas bendahara.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'LPJ-2024-002',
    nomor_rab_terkait: 'RAB-BBD-APK-02',
    kegiatan: 'Pemasangan 250 m2 Banner MMT & Spanduk Strategis Babadan',
    pic: 'Suryadi, S.Sos.',
    kecamatan: 'Babadan',
    desa: 'Desa Ngunut',
    dana_diterima: 4725000,
    nominal_terpakai: 4725000,
    sisa_kas_silpa: 0,
    status_silpa: 'PAS_SESUAI_PAGU',
    foto_bukti: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&auto=format&fit=crop&q=80',
    lokasi: '-7.8250, 111.4700',
    status_audit: 'SAH_SESUAI_KTP',
    catatan_lpj: 'Pemasangan selesai di 45 titik simpul suara. Dana darurat Rp 225.000 terpakai untuk kawat pengikat tambahan.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'LPJ-2024-003',
    nomor_rab_terkait: 'RAB-SMN-CANVASS-03',
    kegiatan: 'Transport Canvassing Door-to-Door Siman & Ronowijayan',
    pic: 'Drs. Hendro Wibowo',
    kecamatan: 'Siman',
    desa: 'Desa Siman',
    dana_diterima: 3150000,
    nominal_terpakai: 3150000,
    sisa_kas_silpa: 0,
    status_silpa: 'PAS_SESUAI_PAGU',
    foto_bukti: 'https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?w=800&auto=format&fit=crop&q=80',
    lokasi: '-7.8900, 111.4900',
    status_audit: 'SELESAI_TEREKONSILIASI',
    catatan_lpj: 'Selesai 100% door-to-door ke 600 KK basis Siman.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  }
];

// Pengajuan RAB Aspirasi
export const SEED_RAB = [
  {
    id: 'RAB-PNG-001',
    nomor_rab: 'RAB-PNG-SAKSI-01',
    nama_kegiatan: 'Alokasi Honorarium & Pelatihan Saksi TPS Ponorogo Kota',
    pos_anggaran: 'HONOR_SAKSI_TPS (Honorarium & Pelatihan Saksi)',
    sumber_data_asal: 'MODUL_SAKSI_TPS (Integrasi Kuota & Standar Honor Saksi)',
    pengaju: 'Budi Santoso, S.Pd.',
    nomor_wa_pj: '081234567891',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Ponorogo (Kota)',
    desa: 'Kelurahan Mangkujayan',
    target_tps_cakupan: 'TPS 001 s/d TPS 045 Ponorogo Kota',
    volume: 120,
    satuan: 'orang saksi',
    harga_satuan_diajukan: 200000,
    subtotal_pokok: 24000000,
    dana_darurat_5persen: 1200000,
    alokasi_pemilih: 25200000,
    target_suara: 9500,
    estimasi_ai: 25200000,
    cpv_unit: 2652,
    status_audit_markup: 'WAJAR_SESUAI_PASAR',
    status: 'DP_CAIR',
    rekening_tujuan: 'BCA 873-509-2211 a.n Budi Santoso',
    bukti_nota_rekening: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop&q=80',
    deskripsi: 'Pagu honorarium 120 Saksi TPS terverifikasi (+ 5% buffer darurat logistik C1 Rp 1.200.000).',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'RAB-PNG-002',
    nomor_rab: 'RAB-BBD-APK-02',
    nama_kegiatan: 'Pemasangan 250 m2 Banner MMT & Spanduk Strategis Babadan',
    pos_anggaran: 'LOGISTIK_BANNER_APK (Spanduk, Baliho, Bendera, Kaos)',
    sumber_data_asal: 'MODUL_LOGISTIK_APK (Integrasi Standar BPS & Target APK Wilayah)',
    pengaju: 'Suryadi, S.Sos.',
    nomor_wa_pj: '081234567896',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Babadan',
    desa: 'Desa Ngunut',
    target_tps_cakupan: '45 Titik Pertigaan & Posko Desa Babadan',
    volume: 250,
    satuan: 'meter persegi (m2)',
    harga_satuan_diajukan: 18000,
    subtotal_pokok: 4500000,
    dana_darurat_5persen: 225000,
    alokasi_pemilih: 4725000,
    target_suara: 1000,
    estimasi_ai: 4725000,
    cpv_unit: 4725,
    status_audit_markup: 'WAJAR_SESUAI_PASAR',
    status: 'DP_CAIR',
    rekening_tujuan: 'BRI 012-345-6789 a.n Suryadi',
    bukti_nota_rekening: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&auto=format&fit=crop&q=80',
    deskripsi: 'Spanduk MMT flexi outdoor 280 gsm pada simpul suara prioritas Babadan (+ 5% buffer perbaikan Rp 225.000).',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'RAB-PNG-003',
    nomor_rab: 'RAB-SMN-CANVASS-03',
    nama_kegiatan: 'Transport Canvassing Door-to-Door Siman & Ronowijayan',
    pos_anggaran: 'TRANSPORT_CANVASSING (Operasional Relawan Door-to-Door)',
    sumber_data_asal: 'MODUL_KORDES_CANVASSING (Integrasi Rute Door-to-Door)',
    pengaju: 'Drs. Hendro Wibowo',
    nomor_wa_pj: '081234567899',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Siman',
    desa: 'Desa Siman',
    target_tps_cakupan: 'TPS 001 - TPS 010 Siman',
    volume: 50,
    satuan: 'orang relawan',
    harga_satuan_diajukan: 60000,
    subtotal_pokok: 3000000,
    dana_darurat_5persen: 150000,
    alokasi_pemilih: 3150000,
    target_suara: 1200,
    estimasi_ai: 3150000,
    cpv_unit: 2625,
    status_audit_markup: 'WAJAR_SESUAI_PASAR',
    status: 'LUNAS',
    rekening_tujuan: 'Mandiri 142-00-123456 a.n Hendro Wibowo',
    bukti_nota_rekening: 'https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?w=800&auto=format&fit=crop&q=80',
    deskripsi: 'Uang bensin relawan canvasser untuk silaturahmi ke 600 KK basis Siman.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'RAB-PNG-004',
    nomor_rab: 'RAB-PNG-HARIH-04',
    nama_kegiatan: 'Mobilisasi & Bantuan Transportasi Pemilih Hari-H TPS A1 Mangkujayan',
    pos_anggaran: 'DANA_MOBILISASI_HARI_H (Bantuan Transport Pemilih TPS A1 / Serangan Fajar)',
    sumber_data_asal: 'MODUL_KONSTITUEN_KTP_A1 (Integrasi Data Pemilih Pasti / DPT A1)',
    pengaju: 'Ahmad Fauzi, S.Kom.',
    nomor_wa_pj: '081234567892',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Ponorogo (Kota)',
    desa: 'Kelurahan Mangkujayan',
    target_tps_cakupan: 'TPS 001, TPS 004, TPS 007 Mangkujayan',
    volume: 380,
    satuan: 'orang pemilih A1',
    harga_satuan_diajukan: 50000,
    subtotal_pokok: 19000000,
    dana_darurat_5persen: 950000,
    alokasi_pemilih: 19950000,
    target_suara: 380,
    estimasi_ai: 19950000,
    cpv_unit: 52500,
    status_audit_markup: 'WAJAR_SESUAI_PASAR',
    status: 'DISETUJUI_BENDAHARA',
    rekening_tujuan: 'BCA 873-112-9988 a.n Ahmad Fauzi',
    bukti_nota_rekening: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800&auto=format&fit=crop&q=80',
    deskripsi: 'Penguncian bantuan transport hadir ke TPS untuk 380 DPT A1 terverifikasi NIK KTP (+5% buffer darurat Rp 950.000).',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  },
  {
    id: 'RAB-PNG-005',
    nomor_rab: 'RAB-BBD-ALERT-05',
    nama_kegiatan: 'Pengadaan Kaos Tambahan Vendor Eksternal Batch 2 (Dalam Audit)',
    pos_anggaran: 'LOGISTIK_BANNER_APK (Spanduk, Baliho, Bendera, Kaos)',
    sumber_data_asal: 'MANUAL_TERVERIFIKASI (Pengajuan Khusus Tim Pemenangan)',
    pengaju: 'Suryadi, S.Sos.',
    nomor_wa_pj: '081234567896',
    provinsi: 'Jawa Timur',
    kota: 'Kabupaten Ponorogo',
    kecamatan: 'Babadan',
    desa: 'Desa Ngunut',
    target_tps_cakupan: 'Simpul Pemilih Babadan',
    volume: 500,
    satuan: 'potong',
    harga_satuan_diajukan: 45000,
    subtotal_pokok: 22500000,
    dana_darurat_5persen: 1125000,
    alokasi_pemilih: 23625000,
    target_suara: 500,
    estimasi_ai: 14700000,
    cpv_unit: 47250,
    status_audit_markup: 'PERINGATAN_MARKUP',
    status: 'PENDING_AUDIT',
    rekening_tujuan: 'BRI 012-345-6789 a.n Suryadi',
    bukti_nota_rekening: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800&auto=format&fit=crop&q=80',
    deskripsi: 'PERINGATAN AUDIT: Harga diajukan Rp 45.000 melampaui standar batas atas BPS Rp 28.000 (+60.7%). Dana ditahan.',
    tenant_id: 'TNT-DEFAULT',
    createdAt: new Date().toISOString()
  }
];
